### ISSUE TITLE
Mounting volumes

### ISSUE THREAD

**Issue by pascalberger** [mriedmann/humhub-docker#10]
How is this container supposed to work with external mounted volumes? I prefere to store the data on a share mounted to the host and mount them to the available volumes. But currently files are written to the volumes during build, and if I afterwards mount empty volums the files are missing. 
I can copy the files created during build to my external shares to have them available, but I'm not sure if this is supposed to work with future updates of this container?

**Comment by mriedmann** [comment]
Hi! Nice to see, that this project is used by some more people.

Currently I do not use this repo but finding a solution to this would be great! In some projects a boot-stepping-script is used to copy files from a build-time directory to the volumes. This would be an easy option but I would really like to find a better alternative.

Got any idea how to solve this? I would really like to have a short discussion about this (manybe bkmeneguello could join us as well)

**Comment by pascalberger** [comment]
@mriedmann @bkmeneguello My goal is to have a compose file for HumHub, containing some containers for mounting some NFS shares to the host which are mounted to container volumes to hold the data, the MariaDB container and the HumHub container. Every container fixed to a specific version by using the according tag in the compose file. If an update is available the compose file would be updated to the new version tag of the container followed by a `docker-compose up`. 

To make this workflow work the HumHub container should be able to write the initial data to its volumes on an initial run, but also update the database and files on an update (by running `php yii migrate/up --includeModuleMigrations=1`).

17.6 added support for the [docker config](https://docs.docker.com/engine/swarm/configs/#simple-example-get-started-with-configs) cmd, but since it was just recently added and as I understand it requires to use Swarm I think going with a boot script is a more generic solution.

**Comment by mriedmann** [comment]
@pascalberger checkout my new [rewrite](https://github.com/mriedmann/humhub-docker/tree/rewrite) branch if you like. It supports "volume priming". Migration support is planed but currently not implemented.

**Comment by bkmeneguello** [comment]
@mriedmann what is the problem with your new "rewrite" branch? Do you need some help to review it or can we proceed to merge?

**Comment by mriedmann** [comment]
Some testing/reviewing would be great. Beside that, the planned "migrating" feature would be highly needed for future updates.

**Comment by stffabi** [comment]
I've tested it. There's a little problem with the permissions of the files.

```
 Permissions - Uploads (Hint: Make /var/www/localhost/htdocs/uploads writable for the webserver/php!)
 Permissions - Module Directory (Hint: Make /var/www/localhost/htdocs/protected/modules writable for the webserver/php!)
 Permissions - Dynamic Config (Hint: Make /var/www/localhost/htdocs/protected/config writable for the webserver/php!)
```

The permissions should be correctly set after the files have been copied over with.
```
  chown -R nginx:nginx /var/www/localhost/htdocs/uploads/
  chown -R nginx:nginx /var/www/localhost/htdocs/protected/modules/
  chown -R nginx:nginx /var/www/localhost/htdocs/protected/config/
```

**Comment by mriedmann** [comment]
@stffabi thank you so much for your help!! I added your suggestions to the rewirte branch. Could you please verify that everything is working correctly now?

**Comment by stffabi** [comment]
@mriedmann thanks so much, works as expected👍
