### ISSUE TITLE
Why not submit InstallCommand to HumHub ?

### ISSUE THREAD

**Issue by madmath03** [mriedmann/humhub-docker#110]
Why not submit [Install Command](https://github.com/mriedmann/humhub-docker/blob/master/humhub/protected/humhub/modules/installer/commands/InstallController.php) to HumHub and close humhub/humhub#3621 at the same time ?

**Comment by mriedmann** [comment]
With https://github.com/humhub/humhub/pull/4345 we are on the way to integrate this.
