### ISSUE TITLE
add migration capability

### ISSUE THREAD

**Issue by mriedmann** [mriedmann/humhub-docker#12]
add a "migration" feature so updated images can use existing volumes

**Comment by mriedmann** [comment]
A possible fix is pushed to the rewrite branch  9e1ade62c043bc419d11b01769bd99832adc7f14 @pascalberger @bkmeneguello maybe you two could test / review this new feature? Would be great!

**Comment by stffabi** [comment]
@mriedmann  thanks for implementing it, I've tested the new functionality and found the following problem: See [comment](https://github.com/mriedmann/humhub-docker/commit/9e1ade62c043bc419d11b01769bd99832adc7f14#r26115827)

**Comment by stffabi** [comment]
There's only one caveat, mounted volumes have to be changed to the new location under `/var/www/...` and config.php has to be changed to reflect the new path.

**Comment by mriedmann** [comment]
@stffabi  you are absolutely right. Do you have some advice how to mitigate this problem?

**Comment by stffabi** [comment]
Hmm, what was your main intention for changing the locations? Did you encounter problems reusing the old `/app/humhub` location?
