### ISSUE TITLE
How to enable "use self-signed SSL certificates" for ldap

### ISSUE THREAD

**Issue by r4nc0r** [mriedmann/humhub-docker#135]
Hi,

i'm trying to host humhub in a docker swarm environment.
We have a self-signed SSL Certificate in our LDAP Domain.

How do i enable self signed SSL Ceritifactes?

**Comment by mriedmann** [comment]
Hi!

I have not played that much with LDAP and HumHub but you can have a look here: https://www.php.net/manual/en/function.ldap-bind.php and try to create an `/etc/openldap/ldap.conf` inside the container (mount or create directly with `docker cp` / `docker exec`).

Maybe @madmath03 can also try to test that on his setup. If not I will try to find some time later this week to test this, if you can find a solution yourself, please post it here. I think other people will also be interested in this.

**Comment by r4nc0r** [comment]
I tried around and you can add
`TLS_CACERT <path-to-cacert>`
or
`TLS_REQCERT ALLOW` (disables SSL certificate checking)
to `/etc/openldap/ldap.conf`

maybe we could add these as enviroment variables to the dockerfile, so it is possible to insert the right cert from the docker-compose or cli?

**Comment by mriedmann** [comment]
Perfect. Yes we can do that. Thx for testing this.
I will leave this open until we have a merged PR, maybe this will take a bit. We have a quite big change in the pipeline so if you need help with an workaround just write here, we will find a temporary solution.

**Comment by r4nc0r** [comment]
Hi,
I finally had some time and startet a pull request #140

**Comment by mriedmann** [comment]
Merged. Thx!
