### ISSUE TITLE
HumHub loading times

### ISSUE THREAD

**Issue by r4nc0r** [mriedmann/humhub-docker#141]
Hi,

we are running Humhub hosted in a Docker Swarm behind a Traefik(Reverse Proxy) with a external MariaDB.
But the loading times are a little Problem. It isnt very slow but also not really responsive. Is there anything that I could do to speed that up? I'm seeing some things about a redis cache, but none of that is documented. 

Greetings

**Comment by mriedmann** [comment]
Hi!

With "loading times" you mean "page load time" not container bootup time right?

For Redis: Yes, there is a redis-caching option implemented. Please have a look at the docker-compose file (https://github.com/mriedmann/humhub-docker/blob/master/docker-compose.yml). Also, we could check the opcache settings. It is likely that we currently do not use opcache (or other opcode caches) per default. Enabling Redis is very likely going to improve performance, especially in a clustered scenario.

Maybe you can have a look at opcaching with humhub. There is an extra opcache package for alpine and maybe its enough to simply install it (https://pkgs.alpinelinux.org/package/edge/community/x86/php7-opcache).

**Comment by r4nc0r** [comment]
Yes I meant loading times.

I enabled redis and it is a little bit faster but still not snappy, is this normal for humhub or does enabling opcache speed things up even more?

I tried installing the `php7-opcache` but it didnt show up in the cache drop down.

Is there anything else that i coul do?

**Comment by mriedmann** [comment]
Ok. Can you give us some absolute numbers (mainly TTFB would be interesting; https://haydenjames.io/analyze-websites-ttfb-time-first-byte/)? 

Humhub has a single-page application design so the first load (especially with empty browser cache) can be a bit long. After that, it should react according to your client's performance (cpu/gpu/memory). Have a look at https://www.humhub.com/de/professional-edition/demo and compare your local performance against there's. If it is similar you should consider asking for optimization advice at the projects main tracker: https://github.com/humhub/humhub/issues.

Besides that, I will have a short look later this week into opcode-caching and how it should work with humhub.

**Comment by r4nc0r** [comment]
TTFB is around 700ms up to 1.5s
The Test Setup is: 
A Docker Swarm with a Mariadb Container and one Humhub Container (no Volume mounts to exclude the issue with slow storage), we have use a Reverse Proxy, But this shouldnt be the Problem because it is very fast and we use it for other Applications on the swarm as well.

**Comment by r4nc0r** [comment]
also I looked into the container and saw that even when I install opcache it is disabled in the php.ini. Is there a way to easily manipulate this file and enable it?
We would need to change variables like 
```php
opcache.enable=1;
opcache.memory_consumption=128;
opcache.interned_strings_buffer=8;
opcache.max_accelerated_files=3000;
```

**Comment by r4nc0r** [comment]
is this possible with the file `base/etc/php7/conf.d/99-custom.ini`?
If so I would be happy to fork and add the changes with according environment variables and README update

**Comment by mriedmann** [comment]
Hi! Yes, this should be possible by adding these lines to the `custom.ini`. You can (maybe even should) add a separate file like `98-opcache.ini` into the directory. Every `ini` file in this directory should be loaded by PHP in startup. Just fork this repo, try it and open a PR if it improves the performance. I am totally willing to add this as an optional feature. Thx for your work!

**Comment by mriedmann** [comment]
@r4nc0r any news on this front? Have you tried enabling opcache?

**Comment by r4nc0r** [comment]
not yet, i was busy sry.

**Comment by r4nc0r** [comment]
we moved our docker containers to new hardware with nvme storage and now the ttfb is 4 times faster. I will look into this in the future, but for now it is looking good. Thanks for all the help!
