### ISSUE TITLE
on installation, let admin creation be failable 

### ISSUE THREAD

**Issue by r4nc0r** [mriedmann/humhub-docker#155]
Hi, 

when I try to run a new Container with an existing DB, the container cannont complete the Installation becaus it tries to create the admin user and fails. Is it possible to make this a recoverable Error and just print an infromation, or check if DB is initialized and skip admin creation?

**Comment by mriedmann** [comment]
Hi! This should not happen as long as an working configuration file is found. Could it be that you are trying to "reinstall" with an empty/new config? We can have a look into this, I just want to check if there is a problem with the "installed-check" or not. Could you please post your config for the existing instance?

**Comment by r4nc0r** [comment]
I dont persist the config directory, because if I do there is this error:
`tail: can't open '/var/www/localhost/htdocs/protected/runtime/logs/app.log': No such file or directory`
I can workaround if I persist the runtime folder too, but that drops performance because I run humhub on a dockerswarm with a glusterfs storage backend and it isnt as fast as if the files were local

**Comment by r4nc0r** [comment]
after some time the error tail:cant open just stops and the container starts working. So this issue is resolved, thanks!

**Comment by mriedmann** [comment]
ok perfect :)

2 small things:
1. Is this related to #141 ? So do you still experience performance issues? Could they that related to slow IO performance?
2. You could use a host directory (non gluster; just local disk) to persist just the runtime dir. There shouldn't life any files that need to be shared between nodes but they can generate serious performance if written to slow storage like the copy-on-write FS outside of volumes or another low IOPS storage.
