### ISSUE TITLE
Does anyone know how can I accelerate the loading speed of the video player in humbhub?

### ISSUE THREAD

**Issue by jimlinntu** [mriedmann/humhub-docker#165]
I do not know if here is a good place to ask this question.
But I just found that the video player was very slow compared to the direct download speed (approximately 1MB per second).
Can anyone give some advices for me to speed up the loading speed of the video player?

**Comment by mriedmann** [comment]
Videos tend to be quite large files. Depending on their resolution and format it can take very high bandwidth and good IO performance to stream them in a "smooth" manner. Please have a look at this post: https://stackoverflow.com/questions/38711282/nginx-slow-static-file-serving-slower-than-node. There are 2 setting in nginx that can be tweaked to improve the performance with big static files like videos (`sendfile_max_chunk` and `worker_processes`; see https://github.com/mriedmann/humhub-docker/blob/master/nginx/etc/nginx/nginx.conf or /etc/nginx/nginx.conf inside the container for current settings).

I would suggest that you set the  `worker_processes` to your CPU count (find with `nproc` or  `lscpu`). Also try to raise the `sendfile_max_chunk` to something like 128k or bigger. Also it is likely (for security reasons) that the delivery of videos is handled by PHP and not directly by nginx. Please have a look at the url the video is loaded from (F12 dev tool in your browser), if you do not care about security that much it could be possible to enable "free" access to the files, boosting the download-speed. 

If you are going to host many videos, I would suggest that you think about using some video-platform (e.g. youtube) or a CDN (e.g. Amazon S3) to host your video-files and only embed them into your pages using iframes or js.

**Comment by jimlinntu** [comment]
Thanks for your thorough explanation!
I am really a newbie to this 😅.
I think I get a rough idea on how to deal with this.
Thank you!

**Comment by jimlinntu** [comment]
For others encountering the same issue as me, I have found a thing called `XSendfile`

https://docs.humhub.org/docs/admin/performance/#x-sendfile
https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/
https://github.com/humhub/humhub/blob/2f8623264ca90e4d57ba7fa0a1479276f6c7d1f1/protected/humhub/modules/file/actions/DownloadAction.php#L96-L111
