### ISSUE TITLE
Unexpected use of tag "latest"

### ISSUE THREAD

**Issue by joserprieto** [mriedmann/humhub-docker#17]
The use of the tag "latest" isn't the expected, or the expected behaviour.

Tagged one image as "latest" is a bad idea for tagged a experimental image.

Use another, like "latest-experimental", or so on.

"latest" is, in the most of cases, the last stable version.

Regards.

**Comment by mriedmann** [comment]
thank you very much for your suggestion! 

I agree with you on the fact that using the "latest" tag on experimental branches is a bad idea. Currently this tag is used on the master branch and is therefor used for "staging" purposes. Experimental changes (as you see in the "rewrite" branch) happen in other branches and are build with the "experimental" tag. 

The reason why I marked the latest-tag as "not recommended" is, that I think using "latest" for productive deployments is a really bad idea. I can't ensure that this container will handle major version upgrades properly, so pulling the latest-tag could result in a unexpected breaking of existing installations.

I would love to see some references on this topic. If you could provide some articles on this topic, I would be very happy to learn that my opinion is flawed. ;-)
