### ISSUE TITLE
Update to PHP 7.2

### ISSUE THREAD

**Issue by ArchBlood** [mriedmann/humhub-docker#171]
In 1.8 the default PHP version is going to be 7.2 just wanted to make sure that this is known

**Comment by mriedmann** [comment]
Currently we are bound to the php7 package of alpine-linux. We are trying to use the latest stable version of alpine and therefore its PHP7 version, which is 7.3.26 for the current release (1.7.1) and 7.4.14 for the upcoming 1.7.2.
Also we are "re-releasing" the latest major versions with the latest alpine/php. So the 1.6 image is also based on new alpine versions.
