### ISSUE TITLE
Change nginx Ping rule to allow external healthchecks

### ISSUE THREAD

**Issue by r4nc0r** [mriedmann/humhub-docker#177]
Hi,
we use a external proxy/loadbalancer in front of our docker services (traefik).
Traefik supports healthchecks and in your nginx.conf you only allow acces to /ping from localhost.

Would it be possible to open this? Maybe by a envrironment variable (e.x. HUMUH_ALLOW_EXTERNAL_HEALTHCHECK) ? 

What do you think? I could implement it if you think it is a good idea 

Greetings

**Comment by mriedmann** [comment]
Hi! 

We have the templating in place to add this feature quite easily. I would suggest that we make a "HUMHUB_REVERSEPROXY_WHITELIST" parameter that defaults to 127.0.0.1. It is very likely that we will have a future requirement to pass down X-Forwarded-* headers which is considered dangerous if no other reverse-proxy is in front of the endpoint. If this happens we can simply use this envvar to enable this.

Just a small note: The current templates is using envsubst and is therefore not capable of handling loops. To disable the whitelist using 0.0.0.0/0 should work, so you can also add ip-addresses and subnets but only one. If we need to support multiple subnets or  addresses we have to extend the templating significantly. 

If you can provide a PR I would be happy to merge it

**Comment by r4nc0r** [comment]
sounds good, i will start working on it this week :)

**Comment by mriedmann** [comment]
Any news on that front? If you need help, just open a WIP PR :wink:
