### ISSUE TITLE
Inconsistence between documentation and tags.

### ISSUE THREAD

**Issue by joserprieto** [mriedmann/humhub-docker#18]
In the README, you put:

> Versions
> 
> latest: unstable master build (not recommended)
> 1.2.2: latest stable release (recommended)
> 1.0.1: latest 1.0.x release (not recommended)
> experimental: test build (testing only)

But on the Docker hub, the last version, is 1.2.0; so, if anyone can use the mriedmann/humhub:1.2.2, he will get a response as:

`ERROR: manifest for mriedmann/humhub:1.2.2 not found`

Please, update the tags / README files.

Regards.

**Comment by mriedmann** [comment]
thank you! 

There was a problem on the docker-hub build process. It should now be possible to pull the recommended tag `1.2.2`
