### ISSUE TITLE
"An unexpected error occurred. If this keeps happening, please contact a site administrator" showed when I uploaded a large file (1.6G) through a 4G network

### ISSUE THREAD

**Issue by jimlinntu** [mriedmann/humhub-docker#189]
Hi, @mriedmann, I am using this repo to host an intranet social network.
May I ask do you know how to resolve this issue?

<img width="1425" alt="Screen Shot 2021-04-05 at 4 33 52 PM copy" src="https://user-images.githubusercontent.com/31609554/113560384-80024e80-9635-11eb-84b7-517bda866d35.png">
<img width="1425" alt="Screen Shot 2021-04-05 at 5 13 24 PM copy" src="https://user-images.githubusercontent.com/31609554/113560395-84c70280-9635-11eb-9d2f-dc3dd6d92265.png">

I also post this issue here: https://github.com/humhub/humhub/issues/4993

**Comment by jimlinntu** [comment]
BTW, my current setting is: `host machine's nginx <-> mriedmann/humhub:1.6.2`

**Comment by mriedmann** [comment]
Sorry for the late reply. If this is only happening with (relatively) slow connections (like 4G) it could be related to the nginx timeout settings. Your screenshots are not showing the response code (network tab > headers > response) or a possible error from the server (network tab > response). Without these it is very hard to debug the actual problem. 

Besides that: If you need to handle files beyond 100MB something like Nextcloud/Owncloud as storage and only posting links in HumHub could be a better solution, especially when dealing with mobile clients and unreliable internet connections.

**Comment by mriedmann** [comment]
Closing that for now. If you need further assistance just write here and I will reopen this issue.
