### ISSUE TITLE
Larger file sizes for local hosted instances?

### ISSUE THREAD

**Issue by geekedtv** [mriedmann/humhub-docker#212]
I used the 

      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 50M

To try and allow larger file sizes but it appears to only allow 16M?
I also tried adding a php.ini file to the root config directory and that didn't seem to fix it either.

When I go into the humhub admin in settings>advanced>files, it still shows 16M as max.

Also, can .mov files be shared from iphones? I would like to do this as well.

**Comment by geekedtv** [comment]
> 
> 
> I used the
> 
> ```
>   PHP_POST_MAX_SIZE: 50M
>   PHP_UPLOAD_MAX_FILESIZE: 50M
> ```
> 
> To try and allow larger file sizes but it appears to only allow 16M?
> I also tried adding a php.ini file to the root config directory and that didn't seem to fix it either.
> 
> When I go into the humhub admin in settings>advanced>files, it still shows 16M as max.
> 
> Also, can .mov files be shared from iphones? I would like to do this as well.

I was able to fix the upload max size but now when I try to upload a video (.mov) it gives an errors

{
    "readyState": 4,
    "responseText": "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n",
    "status": 413,
    "statusText": "Request Entity Too Large"
}

**Comment by mriedmann** [comment]
Can you please make sure that this error is also logged in the humhub/nginx container? Is it possible, that there is another nginx infront of the humhub one?
Also: please give us a bit more information on your setup. Are you using docker or something else (k8s, podman, etc). Are you directly port-forwarding the container or is there more in front of it?

**Comment by ArchBlood** [comment]
I'd just like to note that `upload_max_filesize` can't be larger than `post_max_size` otherwise you'll be thrown such errors so make sure that `POST` is around `256` or more if allowed, it also wouldn't hurt to increase `memory_limit` either,

**Comment by mriedmann** [comment]
The same is true for `NGINX_CLIENT_MAX_BODY_SIZE` please also increase it to `50m` in case. The error you are seeing should be related to the nginx. You can also try to set it to `0` (=unlimited) but this can make you server prone to DOS attacks.
Something similar was described in another issue: https://github.com/mriedmann/humhub-docker/issues/189

**Comment by mriedmann** [comment]
Closing for now, reopen when needed. Feel free to comment here anyway.
