### ISSUE TITLE
Container is waiting for redis, but there is no redis

### ISSUE THREAD

**Issue by alexhorn** [mriedmann/humhub-docker#215]
When I start up my container without setting `HUMHUB_REDIS_HOSTNAME`, it hangs indefinitely:

```
humhub_1  | /docker-entrypoint.sh: Waiting for redis connection...
humhub_1  | /docker-entrypoint.sh: Waiting for redis connection...
humhub_1  | /docker-entrypoint.sh: Waiting for redis connection...
humhub_1  | /docker-entrypoint.sh: Waiting for redis connection...
humhub_1  | /docker-entrypoint.sh: Waiting for redis connection...
humhub_1  | /docker-entrypoint.sh: Waiting for redis connection...
```

It it possible that the hostname is always set to `localhost` in [line 58](https://github.com/mriedmann/humhub-docker/blob/master/docker-entrypoint.sh#L58), which causes it to go into an infinite loop in [line 67](https://github.com/mriedmann/humhub-docker/blob/master/docker-entrypoint.sh#L67)?

**Comment by mriedmann** [comment]
Hi!

There was a quite recent change on the defaults so this is totally possible. I will have a look. What version of the image do you use?

**Comment by mriedmann** [comment]
This should fix it. Will republish the images after the build is trough (can take a bit).

**Comment by alexhorn** [comment]
I'm using version 1.8. It works now, thanks for the fix :)
