### ISSUE TITLE
Chrome Firefox issues

### ISSUE THREAD

**Issue by mriedmann** [mriedmann/humhub-docker#22]
from #20: 
> Dunno if it is humhub itself related or not:
FireFox and Chrome don't work they remain stuck on the first step.
While IE works it returns to start pretty much after every 2 steps orso.

I was able to reproduce the issue, but got no clue what causes this problem. Can someone check against a "non-docker" humhub installation?

**Comment by mriedmann** [comment]
I am working on a fix for this problem. Please look at the [fix-installer](https://github.com/mriedmann/humhub-docker/tree/fix-installer) branch and check if the installer now works for everybody.

**Comment by miloskroulik** [comment]
I'm still having this problem. Output:
```
humhub_1  | - -  14/Feb/2018:20:43:35 +0000 "GET /index.php" 302
humhub_1  | 172.24.0.1 - - [14/Feb/2018:20:43:35 +0000] "GET /index.php?r=installer%2Findex&_pjax=%23layout-content&_=1518640998264 HTTP/1.1" 302 5 "http://127.0.0.1/index.php?r=installer%2Findex%2Fgo" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
humhub_1  | - -  14/Feb/2018:20:43:35 +0000 "GET /index.php" 302
humhub_1  | 172.24.0.1 - - [14/Feb/2018:20:43:35 +0000] "GET /index.php?r=installer%2Findex&_pjax=%23layout-content&_=1518640998265 HTTP/1.1" 302 5 "http://127.0.0.1/index.php?r=installer%2Findex%2Fgo" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-"
humhub_1  | - -  14/Feb/2018:20:43:35 +0000 "GET /index.php" 302
humhub_1  | 172.24.0.1 - - [14/Feb/2018:20:43:35 +0000] "GET /index.php?r=installer%2Findex&_pjax=%23layout-content&_=1518640998266 HTTP/1.1" 302 5 "http://127.0.0.1/index.php?r=installer%2Findex%2Fgo" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" "-
```

**Comment by mriedmann** [comment]
have you tested against the "fix-installer" branch? the "experimental" tag is built from it, the "normal" tags do not include this fix.

**Comment by darookee** [comment]
I have the same problem, the experimental docker image gives this error
```
/usr/local/bin/docker-entrypoint.sh: line 75: syntax error: unexpected "fi" (expecting "then")
```
I guess the `then` is missing [here](https://github.com/mriedmann/humhub-docker/blob/71bd2108f3996e53306a3881e225f9c98cf39582/docker-entrypoint.sh#L73).

**Comment by mriedmann** [comment]
@darookee you are absolutely right. Thank you for reporting this. A new version of the experimental image is building right now.
