### ISSUE TITLE
Registration email not being received, possibly mailer config?

### ISSUE THREAD

**Issue by cybrpimp** [mriedmann/humhub-docker#221]
I've installed using the docker-compose.prod.yml and successfully to the login/registration page.

However, when I register and enter an email, the email is never received so I'm not able to create a user.  I'm wondering if there is some config that need to be made on the mailer.

I'm looking but do not see anything that seems to be an issue.

Do you have any suggestions?

**Comment by mriedmann** [comment]
Thx for your report.
Have a look at this issue https://github.com/mriedmann/humhub-docker/issues/158 
You have several option to enable mailing, currently we do not support "direct" mailing.

**Comment by mriedmann** [comment]
Closing for now, reopen when needed. Feel free to comment here anyway.
