### ISSUE TITLE
Security vulnerabilities in docker image

### ISSUE THREAD

**Issue by djpbessems** [mriedmann/humhub-docker#249]
Please see the following screenshot; the docker image (with tag `:stable`) has several vulnerabilities that can be fixed easily:
<img src="https://user-images.githubusercontent.com/23643312/154337117-ccee621f-14cd-4d45-a43a-6738346ef33d.png" data-canonical-src="https://user-images.githubusercontent.com/23643312/154337117-ccee621f-14cd-4d45-a43a-6738346ef33d.png" width="800" />

This can probably be resolved by an extra step: `apk upgrade --update-cache`; so for example:
```Dockerfile
RUN apk add --no-cache nginx && \
    chown -R nginx:nginx /var/lib/nginx/
```
becomes
```Dockerfile
RUN apk add --no-cache nginx && \
    apk upgrade --update-cache --available && \
    chown -R nginx:nginx /var/lib/nginx/ && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*
```

**Comment by mriedmann** [comment]
I released new latest and stable images => All critical issues should be fixed now. Please open a new issue if there are more/other open vulnerabilities.

Thx for your time and work!
