### ISSUE TITLE
Waiting for database connection...

### ISSUE THREAD

**Issue by nimacodes** [mriedmann/humhub-docker#257]
When I fire up the docker container the start up sequence seems to be stuck in 

/docker-entrypoint.sh: Waiting for database connection...
nc: bad address 'db'

Any ideas what I could have done wrong?

**Comment by dceonline** [comment]
Hi,

try to set **HUMHUB_DB_HOST** to **{localhost IP}:port** of your database server, that worked for me.

**Comment by mriedmann** [comment]
To provide you with appropriate support we would need your docker run parameter or the docker-compose file you are using. I will close this for now. We can reopen it if you need further assistance.
