### ISSUE TITLE
Support push service

### ISSUE THREAD

**Issue by pascalberger** [mriedmann/humhub-docker#27]
Upcoming 1.3 release will support an additional optional [push service](http://docs.humhub.org/admin-push-updates.html). Would be nice to have this supported out of the box by the docker container

**Comment by mriedmann** [comment]
very interesting feature. Thank you for the hint!

I will start a feature-branch for the upcoming 1.3. Integrating NodeJS and Redis directly into this image can lead to a quite heavy rise on resource usage. Further testing is necessary to avoid complications down the road. Maybe a "sidecar" container would be a good idea.

Any suggestions? I'm really no nodeJS/Redis Pro, especially not on apline

**Comment by pascalberger** [comment]
From a deployment perspective multiple containers together with a compose file makes sense IMHO.

**Comment by mriedmann** [comment]
Can someone tell if the push service is stable enought to be used? I can't find the code-repo, https://github.com/humhub/humhub-pushservice gives 404. Any ideas?

**Comment by mriedmann** [comment]
I am closing this for now. Please reopen this issue if the pushservice (+ source-code) is officially released. Thx!
