### ISSUE TITLE
Update to latest Version

### ISSUE THREAD

**Issue by r4nc0r** [mriedmann/humhub-docker#275]
Hi,

is it possible to update the current images to the newest version, there are some bugfixes that we need.

If i can help in any way, just lead me in the right direction :)

Greetings

**Comment by mriedmann** [comment]
Sorry forgot to release after marging https://github.com/mriedmann/humhub-docker/commit/d98dc83702732fd6aab7217111b8deff1b8d8cbc ... all registries should be up-to-date now. Thx for pointing this out.

**Comment by r4nc0r** [comment]
Thanks!
