### ISSUE TITLE
Wrong humhub version

### ISSUE THREAD

**Issue by caumons** [mriedmann/humhub-docker#28]
Hi,

There is a bug while cloning the Humhub official repo from the Dockerfile. It's much better to use the Git tags than branches, for example, version 1.2.4 doesn't have its own branch, but it has its tag. See: https://github.com/humhub/humhub/releases

Here is the patch to fix it. It works perfectly for me:

```
diff --git a/Dockerfile b/Dockerfile
index c84568d..789b7b8 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -45,8 +45,9 @@ RUN chown -R nginx:nginx /var/lib/nginx/ && \
     chmod 777 /var/run/supervisor.sock
 
 RUN mkdir /usr/src && cd /usr/src/ && \
-    git clone --branch $HUMHUB_VERSION https://github.com/humhub/humhub.git humhub && \
+    git clone https://github.com/humhub/humhub.git humhub && \
     cd humhub && \
+    git checkout tags/$HUMHUB_VERSION && \
     sed -i '/YII_DEBUG/s/^/\/\//' index.php && \
     sed -i '/YII_ENV/s/^/\/\//' index.php
```

Hope it helps. Cheers!

**Comment by mriedmann** [comment]
Hi,
thank you for your contribution!

The mentioned line `git clone --branch $HUMHUB_VERSION https://github.com/humhub/humhub.git humhub` is my attempt to avoid cloning the hole repo to reduce the size of the image.

According to a [post on stackoverflow](https://stackoverflow.com/questions/791959/download-a-specific-tag-with-git) `--branch` should also work with tags.

I will have a quick look into this. Thanks again.

**Comment by caumons** [comment]
Hi,

Using `git clone --branch $HUMHUB_VERSION https://github.com/humhub/humhub.git humhub` actually does the checkout to the $HUMHUB_VERSION tagged commit, so you're right in this case. This works since git 1.8.5.2 as stated in the same referenced SO link.

But, I've tested what you say "is my attempt to avoid cloning the hole repo to reduce the size of the image" by generating an image file for both methods and the result is exactly the same size. You can try this yourself to verify if you want.

So, both methods seem to work fine with the same result.

Thanks for your work!
