### ISSUE TITLE
unable to post a content with a picture

### ISSUE THREAD

**Issue by jvies** [mriedmann/humhub-docker#282]
hi all,

I've a new issue on my humhub deployment. The users can't post a message in any space with some joint file.
Adding pictures to any gallery or file sharing on the same humhub works fine.

The error visible from firefox is:

```
{
    "readyState": 4,
    "responseText": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.20.2</center>\r\n</body>\r\n</html>\r\n",
    "status": 502,
    "statusText": "Bad Gateway"
}
```

and from the docker image:
```
humhub_1  | 2022/09/04 07:18:30 [warn] 47#47: *7 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000001, client: 172.18.0.3, server: _, request: "POST /file/file/upload HTTP/1.1", host: "intranet.foo.bar"
humhub_1  | 2022/09/04 07:18:34 [error] 47#47: *7 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.3, server: _, request: "POST /file/file/upload HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "intranet.foo.bar"
humhub_1  | [04-Sep-2022 07:18:34] WARNING: [pool www] child 57 exited on signal 9 (SIGKILL) after 12.663394 seconds from start
```

any idea with what's wrong with my deployment ?

Thx a lot.

**Comment by mriedmann** [comment]
Hi!

As far as I see it, it should not be a timing or size issue. That should generate different messages. A blind guess would be Memory Shortage or something going on with your File handlers or Storage in general. 
Can you also have a look at the Kernel and general system logs? Can you give us a bit more info about your setup? (OS, Memory, Shared Host vs. Dedicated, ...)

**Comment by jvies** [comment]
Thank you ! I just not checked my host logs...
It's an oom issue. I'll see how to increase the host RAM (it's a vhost at OVH).
