### ISSUE TITLE
Issues to enable XSendfile

### ISSUE THREAD

**Issue by jvies** [mriedmann/humhub-docker#283]
Hi,

I'd like to enable the XSendfile on my humhub installation (cf https://docs.humhub.org/docs/admin/performance).
In order to not override the while nginx.conf included within the Docker image, it would be great if this file contained a directive `include /etc/nginx/conf.d/*.conf;` so we can provide additional nginx directives.

Is this OK for you ?
I you want I can try it locally (also to check it still work if /etc/nginx/conf.d is empty), and provide a PR.

Best regards,

**Comment by mriedmann** [comment]
Fine with me. Just issue a PR, will review and merge this. 😊

**Comment by jvies** [comment]
PR is here:
https://github.com/mriedmann/humhub-docker/pull/285
