### ISSUE TITLE
custom themes

### ISSUE THREAD

**Issue by josaur** [mriedmann/humhub-docker#292]
Right now there is no ability to have custom themes within the container. As I see there is no mounting option for the /themes folder. Meaning with every update or restart of the container the changes made in this folder will be gone. So for our purposes it would be nice to have a mount point there (or a subdirectory)  with an extra volume to persist that.

**Comment by r4nc0r** [comment]
as fafr as I know you can mount whatever you like, if you specify that in your docker compose file like: `/path/on/your/machine:/path/inside/container`
