### ISSUE TITLE
Disable debug mode

### ISSUE THREAD

**Issue by bkmeneguello** [mriedmann/humhub-docker#3]
In Administration > Information there is an alert:
"HumHub is currently in debug mode. Disable it when running on production!
See installation manual for more details."
It's possible to start without debug?

**Comment by bkmeneguello** [comment]
http://docs.humhub.org/admin-security.html

**Comment by mriedmann** [comment]
Should be easily possible by adding an postprocessing-script (awk + env). Currently I got very little time, so a pull-request would be appreciated ;-)
