### ISSUE TITLE
profile_image

### ISSUE THREAD

**Issue by GregLeonhardt** [mriedmann/humhub-docker#301]
On initial startup I get an error message stating that directory 'uploads/profile_image' does not have the proper permissions.  When the directory simply does not exist.  Creating the directory is complicated because the permissions of the uploads directory have been changed.  I have to manually create the directory then change it's permissions to get past the initial inspection page.

**Comment by mriedmann** [comment]
Hi! Can you please add the docker-compose you are using? Are you using x86 Linux with Docker or some else (like WSL or Podman)?

**Comment by GregLeonhardt** [comment]
version: '3.1'
services:

  db:
    container_name: db
    restart: unless-stopped
    image: mariadb:10.9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HumHub
      MYSQL_USER: HumHub
      MYSQL_PASSWORD: {REDACTED}
    volumes:
      - "../../volumes/humhub-mariadb:/var/lib/mysql"

  humhub:
    container_name: HumHub
    restart: unless-stopped
    depends_on:
      - db
    image: mriedmann/humhub:1.11.4
#   image: mriedmann/humhub:1.10.5
    links:
      - "db:db"
    ports:
      - "7216:80"
    volumes:
      - "../../volumes/humhub-config:/var/www/localhost/htdocs/protected/config"
      - "../../volumes/humhub-uploads:/var/www/localhost/htdocs/uploads"
      - "../../volumes/humhub-modules:/var/www/localhost/htdocs/protected/modules"
    environment:
      HUMHUB_DB_USER: HumHub
      HUMHUB_DB_PASSWORD: {REDACTED}

**Comment by GregLeonhardt** [comment]
There is more to it.  I was getting a lot of error messages on the console.  They all were because of an inability to open a file for this or that.  Every time I went to look the files were present but they were all owned by root.  After doing globally changing ownership all these problems went away.

From inside the humhub container:
chown -R ngnix:ngnix /var/www/localhost/htdocs
