### ISSUE TITLE
Unable to connect to 'db'

### ISSUE THREAD

**Issue by GregLeonhardt** [mriedmann/humhub-docker#302]
I attempted to change the database server name from 'db:' to something else.  At startup the humhub container would fail to establish communications to 'db'.  This was curious since the docker-compose.yml file contained absolutely no references to 'db'.  I am guessing it is hard coded somewhere else.

**Comment by mriedmann** [comment]
Hi! 

Not hardcoded but defined using defaults: https://github.com/mriedmann/humhub-docker/blob/master/docker-entrypoint.sh 

Just add the right env variables and you should be good to go.

**Comment by GregLeonhardt** [comment]
I set the database host, password etc. during initial configuration.  I should also point out that the database is being initialized with tables etc.  The problem is that after initialization the application attempts to connect to 'db' when it should be connecting to 'HumHub_db'.

The following is the the docker-compose.yml file that fails.
------------------------------------------------------------------------------

version: '3.1'
services:

  HumHub_db:
    container_name: HumHub_db
    restart: unless-stopped
    image: mariadb:10.9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HumHub
      MYSQL_USER: HumHub
      MYSQL_PASSWORD: {REDACTED}
    volumes:
      - "../../volumes/humhub-mariadb:/var/lib/mysql"

  humhub:
    container_name: HumHub
    restart: unless-stopped
    depends_on:
      - HumHub_
    image: mriedmann/humhub:1.11.4
#   image: mriedmann/humhub:1.10.5
    links:
      - "HumHub_:HumHub_"
    ports:
      - "7216:80"
    volumes:
      - "../../volumes/humhub-config:/var/www/localhost/htdocs/protected/config"
      - "../../volumes/humhub-uploads:/var/www/localhost/htdocs/uploads"
      - "../../volumes/humhub-modules:/var/www/localhost/htdocs/protected/modules"
    environment:
      HUMHUB_DB_USER: HumHub
      HUMHUB_DB_PASSWORD: {REDACTED}

**Comment by r4nc0r** [comment]
I think you need to add the environment Variable: `HUMHUB_DB_HOST=HumHub_db` for the humhub service, because the default value is `HUMHUB_DB_HOST=db`
