### ISSUE TITLE
Linkedin module uninstall leads to modules section being lost

### ISSUE THREAD

**Issue by limenleap** [mriedmann/humhub-docker#324]
In a new Humhub docker based installation, I installed the LinkedIn login module.  I configured it and  I realized some issue with the host name... So I uninstalled that module. This resulted in the _entire_ modules route being inaccessible.  If  I tried to go to  https://keralabusiness.network/admin/module/list  it says something about "taking a wrong turn" !!

So I had to start all over again with a fresh install

**Comment by ArchBlood** [comment]
Are you able to access the Information > Logging section?

**Comment by mriedmann** [comment]
Sounds like your hostname was configured incorrectly but without further logs it's hard to help you.

Also, keep in mind that this is not the official humhub issue tracker, you might have more luck posting there or in some plugin related trackers/forums/etc.

Cheers

**Comment by limenleap** [comment]
Yes. I think that was the issue. Thank you very much
