### ISSUE TITLE
SSL Woes

### ISSUE THREAD

**Issue by vorletzter** [mriedmann/humhub-docker#331]
Instance: https://hub.einerunde.de
Version: Stable (1.13.2)

I am not quite sure i the Issue lies with the Container, the HumHub App or HumHub.

I was playing around with HumHub and just wanted to try the new App.  

I added my Traefik Lables to the docker-compose and remove the ports entry

```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.humhub.rule=Host(`hub.einerunde.de`)"
      - "traefik.http.routers.humhub.entrypoints=websecure"
      - "traefik.http.middlewares.humhub-https.redirectscheme.scheme=https"
      - "traefik.http.routers.humhub.tls=true"
      - "traefik.http.routers.humhub.tls.certresolver=leresolver"
      - "traefik.http.routers.humhub.tls.options=myTLSOptions@file"
      - "traefik.http.middlewares.humhub-https.redirectregex.permanent=true"
```

Humhub works fine via ssl. But the App complains about http://hub.einerunde.de - net::ERR_CLEARTEXT_NOT_PERMITTED

I entered http**s**://hub.einerunde.de in the Instance Screen. In HumHub Settings the Base Instance is set to http**s**://hub.einerunde.de as well.

Analysing the Traffic in Firefox i stumbled across some non-SSL? Traefik? But i have no clue what is happening here as well.

![image](https://github.com/mriedmann/humhub-docker/assets/20705858/8fffbafc-455b-47e3-8157-a29282855b9f)

Maybe sombody can shed some light or point me in the right direction :) ?

[docker-compose.yml.txt](https://github.com/mriedmann/humhub-docker/files/13257726/docker-compose.yml.txt)

**Comment by jvies** [comment]
Hello,
I felt into the same issue 2 weeks ago. I was helped by the app team here:
https://github.com/humhub/app/issues/127

You probably don't have your humhub correctly configured for https beyond a reverse proxy as traefik.
cf https://docs.humhub.org/docs/admin/reverse-proxy/#httpsssl-detection

Regards

**Comment by vorletzter** [comment]
Thanks a lot. Helpful!

Can i configure my container to help HumHub with the SSL Detection or do i need to edit the file as suggested?

**Comment by jvies** [comment]
I'm not sure it is possible to configure the Humhub to detect it is beyond

**Comment by vorletzter** [comment]
how did you do that?
Did you clone the whole repository to make the changes permanent to avoid the ephemeral nature of docker?

**Comment by jvies** [comment]
nope, I use docker volumes :
`    volumes:
      - "./config:/var/www/localhost/htdocs/protected/config"
`

**Comment by mriedmann** [comment]
Just my 2 cents: Humhub's architecture is not perfectly aligned with modern "container-centric" applications (see https://12factor.net/). We are doing our best to mitigate this fact, but some features are a bit "weird" because of this fact.

Here is also another hint about the X-Forwarded-Proto header: https://github.com/humhub/humhub/issues/1859
