### ISSUE TITLE
Error launching container - 97: Address family not supported by protocol

### ISSUE THREAD

**Issue by ktdt00** [mriedmann/humhub-docker#348]
Running on host without IPV6 enabled and nginx throws this error:

```
2024/04/23 21:05:03 [emerg] 44#44: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
2024-04-23 21:05:03,270 WARN exited: nginx (exit status 1; not expected)
```

Everything I'm finding tells me to comment out `"listen [::]:80"` in the conf but the readme kinda says not to mess with nginx.conf because it's dynamically created at runtime.

I guess I'm looking for the easiest/bests way around this?

**Comment by mriedmann** [comment]
Thank you for pointing this out ... This is an uncomfortable limitation of the current image. We would need some kind of ipv4only switch on container startup to replace the `listen [::]:80` directive with `listen 80`. To work around this, you can just run `sed -i 's/^listen \[\:\:\]:80$/listen 80/' /path/to/nginx.conf` on your own dockerfile importing from this image and use that on your host.
