### ISSUE TITLE
Unable to login using Repo Config Files

### ISSUE THREAD

**Issue by airlabx** [mriedmann/humhub-docker#35]
I was able to get HumHub running using your config files, running with docker-compose, and when I went to set it up it installed automatically.  Are you able to expand on how the config files setup a default instance and where the admin login would be?

I see on the docker-entrypoint "Writing config file.." but no username or password.

Thanks

**Comment by mriedmann** [comment]
Hi! 

For autoinstall the Username is "admin" with password "test"

This container uses the "autoinstall"-feature originally designed for integration testing. So, the username and password can be found in this file: https://github.com/humhub/humhub/blob/3bcc3e67addbe61852c625891f593dc83b3655e3/protected/humhub/modules/installer/commands/InstallController.php

I will add this to the readme file. 

Thank you very much for your contribution!
