### ISSUE TITLE
Several issues while increasing file upload size

### ISSUE THREAD

**Issue by zell-mbc** [mriedmann/humhub-docker#351]
I tried to increase the upload size for my Humhub uploads and hit multiple issues which I thought I'd mention.

I started with the Humhub UI where I set the limit to 1000M but was told by the admin UI that php reports only 2MB

So I set `PHP_UPLOAD_MAX_FILESIZE: 1024M` in docker-compose.yml which didn't seem to have an effect
After changing the upload_maxfilesize value in /etc/php8/php.ini of the docker container I ended up with a new 8MB max value, which turned out to come from `post_max_size = 8M` in php.ini.
Changed that as well, and also `NGINX_CLIENT_MAX_BODY_SIZE: 1024M` in docker-compose-yml and finally got things working.

But because I need these php.ini changes to persist I had to also pull out php.ini to my local filesystem  '- ./php.ini:/etc/php8/php.ini`
So everything is working for me now but I thought I mention this as a potential subject to address/document.

- PHP_UPLOAD_MAX_FILESIZE for some reason didn't show any effect.
- PHP_POST_MAX_SIZE doesn't exist I think, didn't show an effect at least. But without it PHP_UPLOAD_MAX_FILESIZE is kind of pointless?
- NGINX_CLIENT_MAX_BODY_SIZE: 1024M, that one worked fine

**Comment by jvies** [comment]
I think you have to set them all in your docker-compose.yml:
```
      - PHP_UPLOAD_MAX_FILESIZE=1G
      - PHP_POST_MAX_SIZE=1G
      - PHP_MEMORY_LIMIT=1G
      - NGINX_CLIENT_MAX_BODY_SIZE=1G
```

**Comment by zell-mbc** [comment]
That's where I started, but had to revert to changing php.ini after noticing that the vars didn't work.
```
      - PHP_UPLOAD_MAX_FILESIZE=1G -> Didn't seem to do anything
      - PHP_POST_MAX_SIZE=1G -> Doesn't exist?
      - NGINX_CLIENT_MAX_BODY_SIZE=1G -> Works
 ```

**Comment by dantefromhell** [comment]
My current guess is that this might be related to [99-custom.ini](https://github.com/mriedmann/humhub-docker/blob/master/base/etc/php81/conf.d/99-custom.ini) not having any variable substitution applied during container creation.

In my production humhub instance, the content of the file is exactly the same as in source control
```
# cat /etc/php81/conf.d/99-custom.ini
memory_limit = ${PHP_MEMORY_LIMIT}
max_execution_time = ${PHP_MAX_EXECUTION_TIME}
upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}
post_max_size = ${PHP_POST_MAX_SIZE}
date.timezone = "${PHP_TIMEZONE}"
log_errors = on
error_log = '/proc/self/fd/2'
display_errors = 'stderr'
```

**Comment by jvies** [comment]
According to https://www.php.net/manual/en/configuration.file.php, this syntax is correct.
Moreover, "it works for me " ©

We had issues on this topic on some past versions. Do you use the latest images ?

**Comment by zell-mbc** [comment]
Sorry missed your response, I did use the latest image at the time. Currently on v1.15.2
Can't explain why this wouldn't work for me, I think I'll keep things as they are for now. I think I can always re-open here if I ever get to the bottom of this issue.
