### ISSUE TITLE
CronJobs

### ISSUE THREAD

**Issue by bkmeneguello** [mriedmann/humhub-docker#4]
At Administration > Information > CronJobs there is an alert about cron jobs. They are not configured. It's possible to setup then?

**Comment by mriedmann** [comment]
Thx for your issue-report!

This image uses supervisord, so a cronjob could be added without much afford (https://gist.github.com/martinrusev/7015e393d46647dbad15). I will look into it when I find some time (next month).

An alternative is running the "job" on the docker-machine:
You could try something like `docker exec <container> php /app/humhub/protected/yii cron/hourly` to evade this issue without waiting for a fix
