### ISSUE TITLE
Issues with 1.3.2

### ISSUE THREAD

**Issue by Alea81** [mriedmann/humhub-docker#52]
We have tested 1.3.2:
- Mark down for links not working: `[Link](www.test.com)`
- After a post, the placeholder from the comment section does not vanish, you are standing at the and of that text.

(Maybe these are fixed with humhub version 1.3.7)

Also, there is a vulnerability with Humhub 1.3.6 fixed in 1.3.7 (https://www.humhub.org/de/news/9031)

**Comment by mriedmann** [comment]
_First of all: Thank you very much for your contribution! I merged all your PRs and pushed a new tag (1.3.8) to the docker hub._

Could you please describe your problem a bit more. I am only maintaining the humhub docker image, not the project itself. If this is an issue with Humhub itself it would be better to look at https://github.com/humhub/humhub/issues for help. If it is a docker specific problem, please help me to understand it better.

**Comment by Felli** [comment]
Humhub's new rich text editor doesn't support the manual use of most markdown syntax, linked text being one of them, it's best to use the toolbar for now while it's being fixed, also make sure that you updated as much as possible to keep getting bug fixes as well as new features! :wink:

**Comment by mriedmann** [comment]
Thx @Felli for the clarification! I will close this for now.
