### ISSUE TITLE
PHP Config not enough for big files upload

### ISSUE THREAD

**Issue by maurino** [mriedmann/humhub-docker#59]
Hi,
I tried to set PHP_POST_MAX_SIZE and PHP_UPLOAD_MAX_FILESIZE, in order to upload bigger files on humhub, but it resulted in a "413 Entity too large" http error.

To fix this error, i modified the nginx.conf file, setting
  client_max_body_size 1024m;
and recompiled the container

In order to avoid reconpilation, could this setting be parametrized with PHP_POST_MAX_SIZE too?

Best regards
Mauro

**Comment by mriedmann** [comment]
Hi!

Thank you very much for pointing out this issue. I have planned to implement proper templating with https://github.com/jwilder/dockerize so using this we can easily satisfy your request. I will look into it as soon as I can.

Cheers,
Michael

**Comment by mriedmann** [comment]
As you may see I have added a new env setting called NGINX_CLIENT_MAX_BODY_SIZE to the `latest` tag (currently building; available in 30min max). I hope this was what you had in mind. Please test it and report back if this is not working as expected.

I am closing this, for now. Feel free to add to it or open a new issue.

**Comment by maurino** [comment]
Hi Michael,

thank you for your prompt reply
You fix was exactly what i needed, I have rebuilt the container and works perfectly for me

Best regards
Mauro
