### ISSUE TITLE
Port 443 not responding

### ISSUE THREAD

**Issue by csrui** [mriedmann/humhub-docker#80]
Hi,

I've setup my containers using the composer but added port 443. In my case I never get any response on this. Only port 80. Anyone else has issues with this?

**Comment by mriedmann** [comment]
Hi! The current container only supports http (see https://github.com/mriedmann/humhub-docker/blob/master/etc/nginx/nginx.conf#L36) ... if you want to host humhub via https I would recommend a proxy like traefik (https://docs.traefik.io/) with ssl-offloading capability ... corrently there is no intention to provide a self-signed SSL endpoint but a PR would be appreciated :)

**Comment by mriedmann** [comment]
I will close this for now. Feel free to post I something is still unclear.
