### ISSUE TITLE
Environment Variables do not increase the Upload size to 100M

### ISSUE THREAD

**Issue by maglite4cell** [mriedmann/humhub-docker#92]
Changing these Environment Variables in the docker-compose does not seem to make any difference.  When uploading a large file, it gives an error of max size to 5.243MB

      PHP_POST_MAX_SIZE: '100M'
      PHP_UPLOAD_MAX_FILESIZE: '100M'
      NGINX_CLIENTMAX_BODY_SIZE: '100M'

Error "is too big. Its size cannot exceed 5.243 MB."

**Comment by ArchBlood** [comment]
Did you also change the Maximum upload file size from the HumHub advanced settings?

![Screenshot_1](https://user-images.githubusercontent.com/35392110/80781465-5cd74100-8b40-11ea-9759-63d673bf7f9f.png)
