### ISSUE TITLE
No install process, no default user

### ISSUE THREAD

**Issue by luison** [mriedmann/humhub-docker#98]
Hi. Thanks for your docker install. Trying to get it running but when accessing via browser I get requested to login. I thought an installation process should start and can't guess the default user and password.  
![image](https://user-images.githubusercontent.com/745632/81738048-5084a980-9499-11ea-9014-d64fb7cd34be.png)

**Comment by mriedmann** [comment]
Hi! If you are using the docker-compose inside the repo just remove this line: `HUMHUB_AUTO_INSTALL: 1` 
Please also see the sample in the readme file.

**Comment by mriedmann** [comment]
I will close the issue for now. Feel free to post here again or open a new issue if there are other problems.
